import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "./query-client-provider";
import SessionProvider from "./session-provider";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bodhon",
  description: "Generated by kathulia.org",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.variable} antialiased`}>
        <QueryClientProvider>
          <Theme>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <SessionProvider>{children}</SessionProvider>
            </ThemeProvider>
          </Theme>
          <Toaster />
        </QueryClientProvider>
      </body>
    </html>
  );
}
